apiVersion: v1
kind: ConfigMap
metadata:
  name: env-configmap
data:
  POSTGRES_HOST: cdr.cbbgzpxbiqfe.us-east-1.rds.amazonaws.com
  POSTGRES_DB: postgres
  AWS_REGION: us-east-1
  AWS_PROFILE: default
  AWS_BUCKET: pro3-196343632393
  JWT_SECRET: testing
  URL: localhost:8100